# Generated by Django 5.2.17 on 2026-08-29 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Ombor',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Sotib olish'), ('SALE', 'Sotish'), ('RETURN', 'Qaytarish'), ('ADJUSTMENT_IN', 'Tuzatish (Kirish)'), ('ADJUSTMENT_OUT', 'Tuzatish (Chiqish)'), ('DAMAGE', 'Buzilgan'), ('OTHER', 'Boshqa')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField(help_text="Miqdor o'zgarishi")),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, help_text="Bog'liq hujjat ID", max_length=255)),
                ('reference_type', models.CharField(blank=True, help_text="Bog'liq hujjat turi", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
