# Generated by Django 6.0.4 on 2026-08-30 14:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Naqd'), ('DEBT', 'Nasiya')], db_index=True, default='CASH', max_length=10)),
                ('reference_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Ombor partiyasi',
                'verbose_name_plural': 'Ombor partiyalari',
                'db_table': 'inventory_batches',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='chk_batch_quantity_non_negative')],
            },
        ),
    ]
