# Generated by Django 6.0.4 on 2026-08-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorybatch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='chk_inventory_quantity_non_negative',
        ),
    ]
