# Generated by Django 5.2.17 on 2026-08-29 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('LOW_STOCK', 'Kam qoldiq'), ('OUT_OF_STOCK', 'Tugagan'), ('DEBT_DUE', 'Qarz muddati'), ('DEBT_OVERDUE', "Qarz muddati o'tgan"), ('DEBT_UPCOMING', 'Qarz muddati yaqinlashmoqda'), ('SYSTEM', 'Tizim')], db_index=True, max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null = all users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
