# Generated by Django 6.0.4 on 2026-08-30 14:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('DEBT', 'Nasiya')], default='CASH', max_length=10),
        ),
        migrations.CreateModel(
            name='SupplierDebt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('debt_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('PARTIALLY_PAID', "Qisman to'langan"), ('PAID', "To'langan")], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt', to='suppliers.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi qarzi',
                'verbose_name_plural': 'Yetkazib beruvchi qarzlari',
                'db_table': 'supplier_debts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDebtPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Naqd'), ('TRANSFER', "Pul o'tkazma")], default='CASH', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplierdebt')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_debt_payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Yetkazib beruvchi qarzi to'lovi",
                'verbose_name_plural': "Yetkazib beruvchi qarzi to'lovlari",
                'db_table': 'supplier_debt_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierdebt',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0)), name='chk_supplier_debt_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierdebt',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='chk_supplier_debt_paid_non_negative'),
        ),
    ]
