# Generated by Django 6.0.4 on 2026-09-03 17:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('opened_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_card', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smena Hisoboti',
                'verbose_name_plural': 'Smena Hisobotlari',
                'db_table': 'shift_reports',
                'ordering': ['-closed_at'],
            },
        ),
    ]
