# Generated by Django 5.2.17 on 2026-08-29 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debt'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0)), name='chk_debt_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='chk_debt_paid_non_negative'),
        ),
    ]
