# Generated by Django 5.2.17 on 2026-08-29 10:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlar',
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Hajmi (masalan: 0.5, 0.7, 1.0)', max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('bottle', 'Shisha'), ('L', 'Litr'), ('ml', 'Millilitr'), ('pcs', 'Dona'), ('box', 'Quti'), ('pack', 'Pachka')], default='bottle', max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Sotib olish narxi (UZS)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Sotish narxi (UZS)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_stock', models.PositiveIntegerField(default=5, help_text='Minimal zaxira')),
                ('warning_stock', models.PositiveIntegerField(default=10, help_text='Ogohlantirish darajasi')),
                ('max_stock', models.PositiveIntegerField(default=100, help_text='Maksimal zaxira')),
                ('current_stock', models.IntegerField(default=0, help_text='Joriy zaxira (denormalized)')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
    ]
